services:
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: asc
      POSTGRES_DB: asc
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./resources/asc.sql:/docker-entrypoint-initdb.d/asc.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD: 'True'
      PGPASSFILE: /pgpass
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - ./resources/pgadmin_servers.json:/pgadmin4/servers.json
      - ./resources/pgpass:/pgpass

  node:
    image: node:alpine
    container_name: node
    user: node
    depends_on:
      - db
    ports:
      - "5001:5001"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: ./start_application.sh

volumes:
  pg_data:
